version: "3.9"

services:

# ------------------------------------------------------------------------------
# Agent :: OCR
# ------------------------------------------------------------------------------

  agent_ocr:
    build:
      context: ./agents/ocr
      dockerfile: Dockerfile
    container_name: agent_ocr
    ports:
      - "50051:8080"
    volumes:
      - ./agents/ocr:/app
    working_dir: /app
    networks:
      - complyagent_internal
      - default  # Allow internet access

# ------------------------------------------------------------------------------  
# Agent :: Face  
# ------------------------------------------------------------------------------  

  agent_face:
    build:
      context: ./agents/face
      dockerfile: Dockerfile
    container_name: agent_face
    ports:
      - "50052:8080"
    volumes:
      - ./agents/face:/app
    working_dir: /app
    networks:
      - complyagent_internal
      - default  # Allow internet access
      
  # ------------------------------------------------------------------------------
  # Agent :: NSFW
  # ------------------------------------------------------------------------------
  agent_nsfw:
    build:
      context: ./agents/nsfw
      dockerfile: Dockerfile
    container_name: agent_nsfw
    ports:
      - "50054:8080"
    volumes:
      - ./agents/nsfw:/app
    working_dir: /app
    networks:
      - complyagent_internal
      - default

# ------------------------------------------------------------------------------
# Ollama
# ------------------------------------------------------------------------------
  agent_ollama:
    build:
      context: ./agents/ollama
      dockerfile: Dockerfile
    container_name: agent_ollama
    ports:
      - "50053:11434"
    volumes:
      - ollama_models:/root/.ollama  # persists model cache

# ------------------------------------------------------------------------------
# Networks
# ------------------------------------------------------------------------------

networks:
  complyagent_internal:
    driver: bridge
    internal: true  # No internet access
  default:
    driver: bridge  # Internet access

# ------------------------------------------------------------------------------  
# Volumes
# ------------------------------------------------------------------------------

volumes:
  ollama_models: